### PR TITLE
Upgrades cargo_toml dependency version in `cargo-concordium` to suppo…

### PR DESCRIPTION
**Pull request by rimbi**
…rt edition 2021 smart contracts.

## Purpose

To make `cargo-concordium` support edition 2021 smart contracts.

## Changes

Upgrades cargo_toml dependency version in `cargo-concordium` to support edition 2021 smart contracts.

## Checklist

- [x] My code follows the style of this project.
- [x] The code compiles without warnings.
- [x] I have performed a self-review of the changes.
- [x] I have documented my code, in particular the intent of the
      hard-to-understand areas.
- [ ] (If necessary) I have updated the CHANGELOG.

### CODE REVIEW

**Comment by abizjak** [comment]
@rimbi Have you tested that building and testing contracts works correctly still, with both edition 2018 contracts and edition 2021 contracts?

**Comment by rimbi** [comment]
I have built but not tested the contracts. Do we really need it?

**Comment by rimbi** [comment]
I have done some tests. Apparently, a change in the edition does not make any difference in the produced binary; they have the same hash.

**Comment by abizjak** [comment]
> I have built but not tested the contracts. Do we really need it?

Yes, we did need it to make sure that the tool actually works, to remove any doubts about backwards compatibility.

**Review by abizjak — APPROVED** [review]

**Pull request merged**
